name: Unit test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    # strategy:
    #   matrix:
    #     node-version: [12, 13] # TODO

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: node --version

    - name: Cache node_modules/
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-yarn-cache-

    - run: yarn --frozen-lockfile

    - run: yarn test
      env:
        CI: true
